image: docker:stable
services:
  - docker:stable-dind

variables:
  CI_REGISTRY: dockerhub.ebi.ac.uk
  CI_REGISTRY_IMAGE: dockerhub.ebi.ac.uk/fairification/data-catalogue-demo
  CI_COMMIT_TAG: 0.0.1

stages:
  - build
  - package
  - deploy

npm-build:
  image: node:latest
  stage: build
  script:
    - npm install
#    - npm run test
    - npm run build
  only:
    - ci-test
  when: manual

docker-publish:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - ci-test
  when: manual

k8s-deploy-demo:
  image: dtzar/helm-kubectl:3.11.0
  stage: deploy
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/.dockerconfig.json ./k8s/overlays/demo/
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
#    - echo $KUBE_CONFIG
    - cp .secure_files/config ~/.kube/config
#    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl config view
#    - kubectl config unset contexts
#    - kubectl config unset users
#    - kubectl config unset clusters
#    - kubectl config set clusters.ena-cluster.server $K8_HX_SERVER
#    - kubectl config set clusters.ena-cluster.certificate-authority-data "$K8_HX_CERTIFICATE_AUTHORITY_DATA"
#    - kubectl config set users.ena-admin.token "$K8_HX_USER_TOKEN"
#    - kubectl config set contexts.dc-demo.cluster ena-cluster
#    - kubectl config set contexts.dc-demo.user ena-admin
#    - kubectl config set contexts.dc-demo.namespace dc-demo-dev
#    - kubectl config use-context dc-demo
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - ./kustomize build k8s/overlays/demo
    - kubectl apply -k k8s/overlays/demo --namespace=dc-demo-dev
#  tags:
#    - ena-dcap-gitlab-runner
  only:
    - ci-test
  when: manual

