apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-catalogue-config
  namespace: $K8S_NAMESPACE
data:
  config.js: |
    window.config = {
        "ENVIRONMENT":"demo",
        "REST_ENDPOINT_URL": '/biosamples/samples?filter=attr%3Aproject%20name%3AMICROBE',
        "SCHEMA_ENDPOINT_URL": '/biosamples/schemas/core/sample.json',
        "RESOURCE_JSON_PATH": '_embedded.samples',
        "GRID_CONFIG":  [
            {
                "name": "name",
            },
            {
                "name": "release",
            },
            {
                "name": "organism",
                valueGetter: params => params.data.characteristics?.organism[0].text
            },
            {
                "name": "publication",
                "valueGetter": params => params.data?.publications?.[0]?.pubmed_id
            },
            {
                "name": "project name",
                "valueGetter": params => params.data.characteristics?.["project name"]?.[0]?.text
            }
        ]
    }
