apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: ${K8S_NAMESAPCE}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ${K8S_NAMESPACE}
imagePullSecrets:
  - name: image-pull-secret
